name: Deploy Angular App

on:
  push:
    branches:
      - main  # o master, según tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.11.0'  # Ajusta según tu versión de Node

    - name: Install dependencies
      run: |
        npm install
        npm install -g @angular/cli

    - name: Build and Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ng deploy --base-href=/portfolio/ --name="GitHub Actions" --email=jorgeroldan00.jr@gmail.com --no-silent
